{{- if ne (include "isViewerEnabled" .) "false" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mineflayer-k8s.fullname" . }}
  labels:
    {{- include "mineflayer-k8s.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.config.viewer.loadBalancerIP }}
  ports:
    - port: 3000
      targetPort: viewer
      nodePort: {{ .Values.config.viewer.nodePort }}
      protocol: TCP
      name: viewer
  selector:
    {{- include "mineflayer-k8s.selectorLabels" . | nindent 4 }}
  externalIPs:
    {{- with .Values.config.viewer.externalIPs }}
      {{- range . }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}
{{- end }}